# Modified from https://github.com/Ontotext-AD/graphdb-docker/tree/master
services:
  graphdb:
    container_name: graphdb
    image: ontotext/graphdb:10.6.3
    restart: unless-stopped
    environment: 
      GDB_JAVA_OPTS: >-
        -Xms128g -Xmx256g
        -XX:MaxDirectMemorySize=256G
        -Dgraphdb.global.page.cache=true
        -Dgraphdb.home=/opt/graphdb/home
        -Dgraphdb.page.cache.size=30g
        -Ddefault.min.distinct.threshold=1g
        -Dgraphdb.workbench.importDirectory=/opt/graphdb/home/graphdb-import
        -Dgraphdb.external-url=https://stko-kwg.geog.ucsb.edu/graphdb/
        -Dgraphdb.workbench.cors.enable=true
        -Dgraphdb.workbench.cors.origin=*
        -Denable-context-index=true
        -Dentity-pool-implementation=transactional
        -Dhealth.max.query.time.seconds=600
        -Dgraphdb.append.request.id.headers=true
        -Dreuse.vars.in.subselects=true
    env_file:
      - 'variables.env'
    ports: 
      - 7200:7200
      - 7300:7300
    volumes:
      - ./graphdb/graphdb-data/home:/opt/graphdb/home/
      - ./graphdb/license:/opt/graphdb/home/work
    networks:
      - kwg_network
