# Modified from https://github.com/Ontotext-AD/graphdb-docker/tree/master
services:
  graphdb:
    container_name: graphdb
    image: ontotext/graphdb:10.6.2
    restart: unless-stopped
    environment: 
      GDB_JAVA_OPTS: >-
        -Dgraphdb.home=/opt/graphdb/home
        -Dgraphdb.workbench.importDirectory=/opt/graphdb/home/graphdb-import
        -Dgraphdb.external-url=https://localhost/graphdb/
        -Denable-context-index=true
        -Dentity-pool-implementation=transactional
        -Dhealth.max.query.time.seconds=600
        -Dgraphdb.append.request.id.headers=true
        -Dreuse.vars.in.subselects=true
    volumes:
      - ./graphdb/graphdb-data/home:/opt/graphdb/home/
      - ./graphdb/license:/opt/graphdb/home/work
    env_file:
      - 'variables.env'
    ports: 
      - 7200:7200
      - 7300:7300
    networks:
      - kwg_network