# Modified from https://github.com/Ontotext-AD/graphdb-docker/tree/master

services:
  graphdb:
    container_name: graphdb
    image: ontotext/graphdb:10.7.3
    restart: unless-stopped
    environment: 
      GDB_JAVA_OPTS: >-
        -Xmx144g
        -Dgraphdb.home=/opt/graphdb/home
        -Dgraphdb.workbench.importDirectory=/opt/graphdb/home/graphdb-import
        -Dgraphdb.external-url=https://staging.knowwheregraph.org/graphdb/
        -Dgraphdb.workbench.cors.enable=true
        -Dgraphdb.workbench.cors.origin=*
        -Denable-context-index=true
        -Dentity-pool-implementation=transactional
        -Dhealth.max.query.time.seconds=600
        -Dgraphdb.append.request.id.headers=true
        -Dreuse.vars.in.subselects=true
        -Ddefault.min.distinct.threshold=1G
        -Dgraphdb.page.cache.size=2g
    volumes:
      - ./graphdb/graphdb-data/home:/opt/graphdb/home/
      - ./graphdb/graphdb-data/work/data/V7-SantaBarbara/aboxes-trig:/opt/graphdb/home/import-data
      - ./graphdb/license:/opt/graphdb/home/work
    env_file:
      - 'variables.env'
    ports: 
      - 7200:7200
      - 7300:7300
    networks:
      - kwg_network
