version: '3'
services:
  prometheus:
    image: prom/prometheus:v3.0.1
    volumes:
      - ./prometheus/:/etc/prometheus/
    ports:
      - 9090:9090
    networks:
      - kwg_network
    command:
      - --web.route-prefix=/
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.config.file=/etc/prometheus/web.yml

  node-exporter:
    image: prom/node-exporter
    networks:
      - kwg_network
    ports:
      - 9100:9100
