global:
  scrape_interval: 60s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
  - job_name: node-exporter
    static_configs:
      - targets: [node-exporter:9100]
  - job_name: 'GraphDB Infrastructure Metrics'
    metrics_path: '/rest/monitor/infrastructure'
    scrape_interval: 60s
    static_configs:
      - targets: ['graphdb:7200']
  - job_name: 'GraphDB Data Structures Metrics'
    metrics_path: '/rest/monitor/structures'
    scrape_interval: 60s
    static_configs:
      - targets: ['graphdb:7200']
  - job_name: elasticsearch
    static_configs:
    - targets: ['elasticsearch-exporter:9114']
  - job_name: nginx
    static_configs:
    - targets: ['prometheus-nginx-exporter:9113']
  - job_name: 'kwg-api'
    metrics_path: '/metrics'
    scrape_interval: 30s
    static_configs:
      - targets: ['kwg-api:8080']
