apiVersion: 1

datasources:
  - name: prometheus
    type: prometheus
    url: http://prometheus:9090
    isDefault: true
    access: proxy
    editable: true
    user: admin
      secureJsonData:
        password: 


  - name: Loki
    type: loki
    url: http://loki:3100
    isDefault: false
    access: proxy
    editable: true
