services:
  nginx:
    image: nginx:bookworm
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - 'variables.env'
    volumes:
    - ./nginx/templates:/etc/nginx/templates # NGINX config file
    - ./nginx/sites:/usr/share/nginx/html # Static sites
    - ./nginx/local-certs:/etc/letsencrypt/live/localhost # Local certificates
    depends_on: # These services need to exist for the nginx config to validate
      - graphdb
      - kwg-api
    networks:
      - kwg_network
