services:
  prometheus-nginx-exporter:
    image: nginx/nginx-prometheus-exporter:1.3
    container_name: prometheus-nginx-exporter
    restart: always
    ports:
      - "9113:9113"
    command:
            -nginx.scrape-uri=http://nginx/stub_status
    depends_on:
      - nginx
    expose: 
      - 9113
    networks:
      - kwg_network
